import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

import Analytics from './analytics'

export const metadata = {
  title: 'CL Alpha FFXIV',
  description: 'Generated by create next app',
  metadataBase: new URL('https://www.cl-alpha-ffxiv.fr'),
}


export default function RootLayout({ children }) {

  return (
    <html lang="fr">
      <body className={inter.className}>
        {children}
        {process.env.NEXT_PUBLIC_ANALYTICS_ID != undefined && <Analytics analytics_id={process.env.NEXT_PUBLIC_ANALYTICS_ID} analytics_url={process.env.NEXT_PUBLIC_ANALYTICS_URL} />}
      </body>
    </html>
  )
}
