import './globals.css'
import { Inter } from 'next/font/google'
import { FreeCompany, FCMembers } from "@xivapi/nodestone";
import { GetCompanyMembers } from '@/lib/parser';

const inter = Inter({ subsets: ['latin'] })

import Menu from './menu'
import CustomSWRConfig from './SWRConfig'
import Analytics from './analytics'

export const metadata = {
  title: 'CL Alpha FFXIV',
  description: 'Generated by create next app',
  metadataBase: new URL('https://www.cl-alpha-ffxiv.fr'),
}


export default async function RootLayout({ children }) {
  const fc = new FreeCompany()
  const fcm = new FCMembers()
  const myfc = await fc.parse({ params: { fcId: process.env.NEXT_PUBLIC_FCID } })
  const myfcm = await fcm.parse({ params: { fcId: process.env.NEXT_PUBLIC_FCID } })
  const fallback = {
    'https://xivapi.com/freecompany/9231253336202720275?data=FCM': {
      FreeCompany: { ...myfc, Server: myfc.World },
      FreeCompanyMembers: myfcm.List.map(elem => ({ ...elem, Rank: elem.FcRank, RankIcon: elem.FcRankIcon }))
    }
  }
  fallback[`${process.env.NEXT_PUBLIC_URL}/api/freecompany/9231253336202720275/members.json`] = await GetCompanyMembers()

  return (
    <html lang="fr">
      <body className={inter.className}>
        <Menu />
        <div className="header-top text-slate-100 pt-32">
          <div className="container mx-auto">
            <h1 className="text-2xl">Final Fantasy XIV</h1>
            <h2 className="text-3xl">Les Alpha</h2>
            <small className="text-lg">Compagnie libre sur le serveur Phoenix</small>
          </div>
        </div>

        <CustomSWRConfig fallback={fallback}>{children}</CustomSWRConfig>

        <div className='bg-black text-gray-400 py-8'>
          <div className='container mx-auto'>&copy; Bontiv pour la compagnie libre des Alpha de Phoenix - Final Fantasy XIV et toutes les images sont la propriété de Square Enix.</div>
        </div>
        {process.env.NEXT_PUBLIC_ANALYTICS_ID != undefined && <Analytics analytics_id={process.env.NEXT_PUBLIC_ANALYTICS_ID} analytics_url={process.env.NEXT_PUBLIC_ANALYTICS_URL} />}
      </body>
    </html>
  )
}
